### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by luilver** [Knales/knales.github.io#1]
#### ToDo

- [ ] change 'cup' by 'CUP'
- [ ] link SMS-MT to English version of wiki
- [ ] update '© 2016' 😄
- [ ] broken link to «Knales' GitHub repo»

Thanks to: @mmoya
